### PR TITLE
Fix IMU, Sonar and Bar30 in simulation

### LINKED ISSUE #93: Fix the angular_velocity data in simulation
Currently, the drift parameters for the angular velocity data are being extracted in the following lines in the imu_odometry_node.py file in the main repository for IMU calibration. 
``` 
        corrected_angular_velocity = Vector3(
            imu_msg.angular_velocity.x - self.drift[0],
            imu_msg.angular_velocity.y - self.drift[1],
            imu_msg.angular_velocity.z - self.drift[2]
        )

```

However, since the IMU data we are receiving in the simulation environment is already pre-processed by the plugin, we need to reapply these drift parameters.

### PR DESCRIPTION
**Pull request by talhabw**
- revert joint types from `revolute` to `fixed`
- add drift to IMU data
- remove namespace at the start of the sonar topic name

Closes #93

### CODE REVIEW

File: auv_sim/auv_sim_bridge/include/auv_sim_bridge/simulation_mock_ros.h [hunk 1]
```diff
@@ -220,6 +242,7 @@ class SimulationMockROS {
   void initializeSubscribers() {
     depth_sub_ =
         nh_.subscribe("pressure", 1, &SimulationMockROS::depthCallback, this);
+    imu_sub_ = nh_.subscribe("imu", 1, &SimulationMockROS::imuCallback, this);
```
Comment (senceryazici) [inline auv_sim/auv_sim_bridge/include/auv_sim_bridge/simulation_mock_ros.h:245]: Perhaps 

imu_raw or imu_input is more appropriate here.

File: auv_sim/auv_sim_bridge/include/auv_sim_bridge/simulation_mock_ros.h [hunk 2]
```diff
@@ -211,6 +232,7 @@ class SimulationMockROS {
 
   void initializePublishers() {
     depth_pub_ = nh_.advertise<std_msgs::Float32>("depth", 1);
+    imu_pub_ = nh_.advertise<sensor_msgs::Imu>("imu/data", 1);
```
Comment (senceryazici) [inline auv_sim/auv_sim_bridge/include/auv_sim_bridge/simulation_mock_ros.h:235]: Similarly, drifted_imu? Or imu_drifted?

File: auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/sonar.urdf.xacro [hunk 3]
```diff
@@ -1,11 +1,11 @@
 <?xml version="1.0"?>
 <robot name="sonar" xmlns:xacro="http://ros.org/wiki/xacro">
-  <xacro:macro name="sonar_sim" params="name">
+  <xacro:macro name="sonar_sim" params="name topic">
     <gazebo reference="${name}_link">
       <sensor type="ray" name="${name}">
         <pose>0 0 0 0 0 0</pose>
         <visualize>false</visualize>
-        <update_rate>10</update_rate>
+        <update_rate>20</update_rate>
```
Comment (senceryazici) [inline auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/sonar.urdf.xacro:8]: This comment is totally unnecessary but in case if you wanted to further optimize your design, you can obtain this update rate as parameter.

File: auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/sonar.urdf.xacro [hunk 4]
```diff
@@ -22,9 +22,9 @@
             </vertical>
           </scan>
           <range>
-            <min>0.5</min>
-            <max>30.0</max>
-            <resolution>0.15</resolution>
+            <min>0.3</min>
```
Comment (senceryazici) [inline auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/sonar.urdf.xacro:25]: Or course, just as the update rate, these can be parameters as well. But I think these changes are for a future PR in order to keep the context of this PR small and addressable enough.

File: auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro [hunk 5]
```diff
@@ -1,12 +1,34 @@
...
+
     <gazebo>
       <plugin filename="libuuv_gazebo_ros_imu_plugin.so"
         name="${name}_imu_plugin">
         <robot_namespace>${namespace}</robot_namespace>
-        <link_name>${name}_link</link_name>
-        <sensor_topic>sensors/imu/data</sensor_topic>
+        <link_name>${name}_sim_link</link_name>
+        <sensor_topic>sim/imu</sensor_topic>
         <gyroscope_noise_density>0.0002514074</gyroscope_noise_density>
```
Comment (senceryazici) [inline auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro:32]: Are these ip to date with the imu's actual parameters or our estimation?

**Review by senceryazici — APPROVED** [review]

File: auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/sonar.urdf.xacro (hunk 4 above)
Comment (talhabw) [reply auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/sonar.urdf.xacro:25]: like you said, there are a lot of hard coded values/specifications in the sensors that could be parameters, this may be a future task

File: auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro (hunk 5 above)
Comment (talhabw) [reply auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro:32]: if you meant the noise values, they are the same as our legacy codebase. I can find the noise density values in the sensor specifications but other values like random_walk, bias_correlation_time and turn_on_bias_sigma are not specified in the documents. Not sure what are those or how can we estimate them. This is probably worth an investigation.

Comment (senceryazici) [reply auv_sim/auv_sim_description/auv_common_sim_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro:32]: I think this PR's context can be kept around adding interfaces and links for the sensors, we can address those later.

**Comment by senceryazici** [comment]
there are some conflicts, this can be merged after fixing them
